version: '3.8'
services:
  dev-db:
    image: postgres
    env_file:
      - development.env
    container_name: blockchain-dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  test-db:
    image: postgres
    env_file:
      - test.env
    container_name: blockchain-test
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}