version: '3.8'
services:
  dev-db:
    image: postgres
    env_file:
      - development.env
    container_name: blockchain-dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: process.env.DEV_DB_USERNAME
      POSTGRES_PASSWORD: process.env.DEV_DB_PASSWORD
      POSTGRES_DB: process.env.DEV_DB_NAME